### ISSUE TITLE
OutOfMemoryError while training the cross-encoder

### ISSUE THREAD

**Issue by kunalr97** [hpi-dhc/xmen#22]
```python
train_args = CrossEncoderTrainingArgs(num_train_epochs = 5)

rr = CrossEncoderReranker()
output_dir = f'../outputs/{label2dict[label]}_index/cross_encoder_training/'

rr.fit(
    train_dataset = train,
    val_dataset = val,
    output_dir= output_dir,
    training_args = train_args,
    show_progress_bar = False
)
``` 
When i try to train the cross encoder on the BRONCO dataset for prediciting the ICD code for the diagnoses entities. I get this error:

> OutOfMemoryError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 15.77 GiB total capacity; 14.34 GiB already allocated; 379.12 MiB free; 15.03 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I tried running this line and it does not seem to work. Also there are not any other processes running on the GPU.

```python
import torch
torch.cuda.empty_cache()
```

Thanks in advance for your help.

**Comment by phlobo** [comment]
Hello! 

The cross-encoder is indeed quite memory intensive. Two things that might work:

1) I'm not sure if all memory allocated by SapBERT would be cleared by `empty_cache()`, you might instead want to save the candidate dataset to disk and restart the process / notebook to make sure CUDA memory is entirely freed up. 

2) You can reduce the memory footprint of the cross-encoder by reducing the number of candidates subject to re-ranking (which equals the batch size) to something like 16 instead of 64.

**Comment by kunalr97** [comment]
Hi,       
Thanks for your quick response. I will try this and hope that it works. Where exactly do i need to do this ?                                                                                                                                    

> 2\. You can reduce the memory footprint of the cross-encoder by reducing the number of candidates subject to re-ranking (which equals the batch size) to something like 16 instead of 64.

Thanks in advance

**Comment by kunalr97** [comment]
Thanks a lot! I don't get that error now.
