### ISSUE TITLE
Linking to MedDRA Ontology

### ISSUE THREAD

**Issue by kunalr97** [hpi-dhc/xmen#24]
I am already using your tool to link German Clinical Text to ICD10, OPS, ATC, etc and it is of great help so far. I am further looking to explore more ontologies and one of them would be MedDRA. I am aware that it is part of the UMLS Metathesarus group: https://www.nlm.nih.gov/research/umls/sourcereleasedocs/current/MDR/sourcerepresentation.html. Just couldn't figure out how to create a config file for this from scratch ? I am a bit confused on what to fill in the semantic_types and sabs section of the config file. I hope I was clear enough. In the bigger picture, I want to feed it clinical text in German and and link the medical entities to a MedDRA ontology.

Thanks in advance for your answer.

**Comment by phlobo** [comment]
Since I figured it might indeed be a rather common use case, I added a very simple implementation for this (in branch [meddra](https://github.com/hpi-dhc/xmen/tree/meddra)):

https://github.com/hpi-dhc/xmen/blob/meddra/examples/dicts/umls_source.py
https://github.com/hpi-dhc/xmen/blob/meddra/examples/conf/meddra_german.yaml

Then you can do `xmen dict examples/conf/meddra_german.yaml --code examples/dicts/umls_source.py`

and:

```python
kb = load_kb('/path/to/my/meddra_german.jsonl')
kb.cui_to_entity['10062194']
```

```
CUI: 10062194, Name: Metastasis
Definition: None
TUI(s): 
Aliases (abbreviated, total: 15): 
	 Metastasis, Metastases NOS, Metastase, Metastase, Metastasen NNB, Secondary carcinoma, Sekundaeres Karzinom, Secondary malignant neoplasm of other specified sites, Sekundaere boesartige Neubildung sonstiger spezifischer Stellen, Secondary carcinoma (known primary)
```

Please let me know if this works for you.

**Comment by kunalr97** [comment]
Incredible! Thanks a ton, I tried and it works. Slowly getting to know features of xmen one by one
