### ISSUE TITLE
BRONCO Example Notebook

### ISSUE THREAD

**Issue by phlobo** [hpi-dhc/xmen#8]
- Preparation: Get BRONCO, run commands dict / index
- Run Candidate Generator (maybe just SapBERT)
- Train Cross Encoder
- Evaluate

- Show how to easily replace ATC with MUGIT / SNOMED (cannot evaluate anything, of course)

Note: please check for arbitrary design choices and missing documentation as you go along.

**Comment by nachollorca** [comment]
You can check a simple SapBERT-only example for semantic class TREATMENT [here](https://github.com/hpi-dhc/xmen/blob/bronco_nb/notebooks/BRONCO.ipynb).

If you rather have me joining all three dictionaries for the three semantic classes and run with that, let me know. I did not do it because there is a bug with the ATC dict making the candidate generation fail. Some CUIs are "None", but I did not yet find why.

If the TREATMENT example makes sense to you, I can train five models with each combination of kfolds for 20 epochs or so and output final average+std.
